name: Test workflows inputs - Caller

on:
  workflow_dispatch:
    inputs:
      test_boolean:
        description: "Test boolean"
        type: boolean
        required: true
        default: false
      test_string:
        description: "Test string"
        type: string
        required: true
        default: "test string"

jobs:
  display-inputs:
    uses: ./.github/workflows/inputs-tests.yml
    with:
      test_boolean: ${{ inputs.test_boolean }}
      test_string: ${{ inputs.test_string }}
