name: Test workflows inputs - Caller

on:
  workflow_dispatch:
    test_boolean:
      description: "Test boolean"
      type: boolean
      required: true
      default: false
    test_string:
      description: "Test string"
      type: string
      required: true
      default: "test string"
    test_int:
      description: "Test string"
      type: number
      required: true
      default: 123

jobs:
  display-inputs:
    uses: ./.github/workflows/inputs-tests.yml
    with:
      test_boolean: ${{ input.test_boolean }}
      test_string: ${{ input.test_string }}
      test_int: ${{ input.test_int }}
