name: Test workflows inputs

on:
  workflow_call:
    inputs:
      test_boolean:
        description: "Test boolean"
        type: boolean
        required: true
        default: false
      test_string:
        description: "Test string"
        type: string
        required: true
        default: "test string"
  workflow_dispatch:
    inputs:
      test_boolean:
        description: "Test boolean"
        type: boolean
        required: true
        default: false
      test_string:
        description: "Test string"
        type: string
        required: true
        default: "test string"

jobs:
  display-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump inputs context
        id: github_inputs_step
        run: echo '${{ toJSON(inputs) }}'

      - name: "Display inputs"
        run: |
          echo ${{ inputs.test_boolean }}
          echo ${{ inputs.test_string }}

      - name: "test_boolean - true as boolean"
        if: inputs.test_boolean == true
        run: echo ${{ inputs.test_string }}

      - name: "test_boolean - true as string"
        if: inputs.test_boolean == 'true'
        run: echo ${{ inputs.test_string }}

      - name: "test_boolean - false as boolean"
        if: inputs.test_boolean == false
        run: echo ${{ inputs.test_string }}

      - name: "test_boolean - false as string"
        if: inputs.test_boolean == 'false'
        run: echo ${{ inputs.test_string }}
